### PR TITLE
Add confirmation message for delete account

### LINKED ISSUE #317: Add confirmation message before deleting account
**Actual Behaviour**
There is no confirmation message before deleting the account.

**Expected Behaviour**
There should be a confirmation message before deleting the account

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by PrP-11**
Fixes #317 

Changes: Add confirmation message before deleting account

Surge Deployment Link: https://pr-318-fossasia-susi-accounts.surge.sh

Screenshots for the change:
d1

### CODE REVIEW

**Comment by PrP-11** [comment]
@DNS-404 @akshatnitd @anshumanv @hkedia321 @AnupKumarPanwar Please review

**Comment by PrP-11** [comment]
@DNS-404 In the accounts tab in settings, click on the deactivate your account option. It will take you to delete-account page and will verify the user with your password. After you enter your password and click on delete account then you will get the confirmation message.

**Comment by mariobehling** [comment]
Please add a full stop at the end of the sentence .. "delete my account".

**Comment by PrP-11** [comment]
@mariobehling Made the changes

**Pull request merged**
