### PR TITLE
Email field clears after clicking on cancel

### LINKED ISSUE #723: Clear Email field after cancel button in clicked.
**Actual Behaviour**

When a user clicks on forget password on the homepage, A model opens with an Email field. If you enter email and then click on cancel and then again visit forget password model you will find the email id there.

**Expected Behaviour**

Email field should become empty once a user clicks on the cancel button.

**Steps to reproduce it**

1) Visit https://accounts.susi.ai/
2) Click on forget password.

**Would you like to work on the issue?**

Yes, I would like to work on this.

### PR DESCRIPTION
**Pull request by plxity**
Fixes #723 

Changes: Email field clears itself after the cancel button is clicked.

Surge Deployment Link: https://pr-724-fossasia-susi-accounts.surge.sh

### CODE REVIEW

**Comment by plxity** [comment]
@akshatnitd @anshumanv  Please review this.

**Comment by plxity** [comment]
Oh, why is to so?

**Comment by neeraj3029** [comment]
I think that is better to have the previous email entered when you click on forget password, as there is a high chance that the email will be the same. Hope you got my point.

**Comment by plxity** [comment]
Apparently if you check any web application having forget password option. The email field clears itself when cancel button in clicked.
Check GitHub.com for example.

**Comment by neeraj3029** [comment]
If that is the case, it might be good to go ahead with it.

**Comment by plxity** [comment]
@akshatnitd @anshumanv Please review this.

**Pull request merged**
