### PR TITLE
Implement save changes to server

### LINKED ISSUE #284: Settings page does not save changes
The settings page at https://accounts.susi.ai/settings does not save changes made. Please help to fix this.

### PR DESCRIPTION
**Pull request by PrP-11**
Fixes #284 

Changes: Implement save changes to server

Surge Deployment Link: https://pr-286-fossasia-susi-accounts.surge.sh

Screenshots for the change:
NA

### CODE REVIEW

**Comment by PrP-11** [comment]
@DNS-404 It's working fine for me. Please reload/ refresh the page and try again because it doesn't make sense that it works on password tab and not for account tab because whenever we click on a tab only the values of settings div changes and not the complete page.
s1

**Comment by anshumanv** [comment]
Sorry about the stale review, accidentally approved, please make the changes then this can be approved.

**Comment by PrP-11** [comment]
@anshumanv I am aware that the mobile tab's changes are not reflected on chat.susi, this is a problem with chat.susi that it is not fetching the mobile number correctly. I have opened an issue #[1378](https://github.com/fossasia/chat.susi.ai/issues/1378)  and will fix it. Accounts.susi successfully changes the mobile on the server.

**Comment by DNS-404** [comment]
@PrP-11 No, you got it wrong. Sorry I didn't put it clearly. The second screenshot of my review is misleading about username. 😅 I didn't mean that it's working on password tab but not on account tab. I tried logging out and then logging in again several times. Sometimes my username is displayed and sometimes it's not. Although I do see it if I switch tabs or refresh the page. This can be because username is fetched from server but not rendered in DOM sometimes here and when I change the tab, react looks for all the changes in virtual DOM and then renders them. That's why the username is displayed then. This can be the reason but I am not 100% sure. Here's a GIF of when it's not displayed -
jun-23-2018 10-11-09

**Comment by PrP-11** [comment]
@DNS-404 It is not a problem with rendering, it is working fine for me. This can be due to some connectivity or network issues or may be something with your browser. Also the username is fetched from cookies so maybe clearing older cookies might work for you. You can see below that it is displayed the same time as soon as the page loads. Lets see if others have this issue or not.
s1

**Comment by PrP-11** [comment]
@anshumanv I have opened as issue #287 for the speech tab and will fix it.

**Pull request merged**
