### PR TITLE
Corrected padding and responsive in the settings page

### LINKED ISSUE #653: No padding in settings page
**Actual Behaviour**

There is no padding in the settings page.

**Expected Behaviour**

Provide some padding between the elements in the settings page.

**Screenshots of the issue**

pas

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #653 

Changes: Provide padding between the elements in the settings page. Corrected responsiveness.

Surge Deployment Link: https://pr-654-fossasia-susi-accounts.surge.sh

Screenshots for the change:
pad

### CODE REVIEW

**Comment by samagragupta** [comment]
@neeraj3029 @sakshee-19 @sk9331657 Done the changes.
Please review.

**Comment by anshumanv** [comment]
Looks good, While you're at it, Make everything take up full horizontal space in case everything is vertical
image

**Comment by anshumanv** [comment]
And a margin below the save button

**Comment by samagragupta** [comment]
@anshumanv Done the required changes.

**Comment by samagragupta** [comment]
@anshumanv @sk9331657 Please review.

**Comment by samagragupta** [comment]
@sk9331657 Done 😄

**Comment by samagragupta** [comment]
@Akshat-Jain @akshatnitd Please review

**Comment by samagragupta** [comment]
@anshumanv @Akshat-Jain Please review

**Pull request merged**
