### PR TITLE
Pop-up dialog box implemented when password or email is incorrect

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes issue #169 
Changes: 
Implemented a pop-up dialog box when password or email is incorrect.

Surge Deployment Link: http://dialog-box.surge.sh/

Screenshots for the change:
screen shot 2018-03-02 at 3 08 18 am

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@dynamitechetan Sorry,I did not check on that.I'll make the same with Material Design.

**Comment by DravitLochan** [comment]
@harsh-jindal updates?

**Comment by harsh-jindal** [comment]
@DravitLochan I'm working on it. Had exams going on so couldn't work on it.

**Comment by harsh-jindal** [comment]
@DravitLochan Please review this.

**Comment by DravitLochan** [comment]
@dynamitechetan review this please.

**Comment by DravitLochan** [comment]
@harsh-jindal Please resolve the conflicts

**Comment by harsh-jindal** [comment]
@DravitLochan Conflicts Resolved.

**Pull request merged**
