### PR TITLE
Added responsive design for SignUp page

### LINKED ISSUE #489: Add responsive design for SignUp page
**Actual Behaviour**

When window size is decreased , the arrangement of the sign up page gets distorted .

**Expected Behaviour**

When window size is decreased then the elements of the sign up page should be properly arranged . 

**Steps to reproduce it**

Decrease the width of the screen .

**Screenshots of the issue**

signup page

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #489

Changes: When screen size of sign up page is decreased the elements are arranged properly .
Surge Deployment Link: https://pr-490-fossasia-susi-accounts.surge.sh

Screenshots for the change:
signup page

### CODE REVIEW

**Comment by samagragupta** [comment]
Ok , I will do it .

**Comment by samagragupta** [comment]
signup page

**Comment by rossoskull** [comment]
Try to squash multiple commits.

**Comment by samagragupta** [comment]
@akshatnitd  Its the login page and I have done changes in signup page .

**Comment by samagragupta** [comment]
Squashed the commits

**Pull request merged**
