### PR TITLE
Improve ResetPassword component

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes issue #158 

Changes: Add 'Email' as floating text and not as normal text and fixed some indentations too.

Surge Deployment Link: http://accsusi158.surge.sh/

Screenshots for the change:
image

### CODE REVIEW

**Comment by anshumanv** [comment]
@DravitLochan @rishiraj824 please review. :smile:

**Comment by anshumanv** [comment]
@mariobehling please review. :smile:

**Comment by DravitLochan** [comment]
@anshumanv Don't allow the user to update the email id here.

**Comment by anshumanv** [comment]
Okay @DravitLochan, I'll update. :smile:

**Comment by anshumanv** [comment]
@DravitLochan Added commit to not be able to change email textfield, squashed commits, re-deployed.
Please see. :smile:

**Comment by DravitLochan** [comment]
update the screenshot as well please 👍

**Comment by anshumanv** [comment]
Alright, Updated screenshot as well. @DravitLochan Please see.

**Comment by anshumanv** [comment]
@mariobehling please see and merge. Thanks! :smile:

**Comment by anshumanv** [comment]
@DravitLochan who else can I ask for a review?

**Comment by DravitLochan** [comment]
@rishiraj824 Please review!

**Pull request merged**
