### PR TITLE
Adding responsiveness to login page #237

### PR DESCRIPTION
**Pull request by SudhanvaMG**
Surge Deployment Link: responsive-login.surge.sh

### CODE REVIEW

**Comment by SudhanvaMG** [comment]
@harsh-jindal this is solve the responsiveness of the login icons .

**Comment by harsh-jindal** [comment]
@SudhanvaMG Please make the changes in the pull request where you have added icons.

**Comment by SudhanvaMG** [comment]
@harsh-jindal these changes is not related to the icons . This make the login card responsive , which in turn makes the icons responsive . So i think adding these changes to the icons PR would not be appropriate .

**Comment by DravitLochan** [comment]
conflicts!

**Comment by mariobehling** [comment]
Closing this due to inactivity. The issues have not been resolved after a long time. Thanks.

**Pull request closed without merging**
