### PR TITLE
Made the UI for download files application

### PR DESCRIPTION
**Pull request by DravitLochan**
First step to #43 

changes : made  the UI ready.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a screenshot and link to a test set up.

Now that this project is established please follow best practices.

**Comment by DravitLochan** [comment]
fireshot capture 7 - download files only f_ - http___localhost_accounts susi ai_apps_downloadfiles_

**Comment by mariobehling** [comment]
New UI components should follow the web chat app and not the old loklak UI.

**Comment by DravitLochan** [comment]
Ok. So I think that adding new apps right now is not the priority and updating the framework is. So Let me close this pr and focus on upgrading. Let us include it in the new one only and not this one!

**Pull request closed without merging**
