### PR TITLE
Add all webclient settings and improved UI for settings page

### LINKED ISSUE #266: Add user's web app settings to accounts.susi
**Actual Behaviour**
Currently on the logged In page we see 4 icons of iOS, android, web and cms. Clicking on Web takes us to an empty page.

**Expected Behaviour**
When a user clicks on the Web icon, a page with user's web app settings should be displayed.

**Screenshots of the issue**
a1

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by PrP-11**
Fixes #266 

Changes: 
- Add all settings of webclient
- Removed Change Password option from hamberger menu
- Add Change password tab in settings page itself
- Add icons for all tabs
- Implement Similar UI as of chat.susi settings
- Implement grey background

Surge Deployment Link: http://squeamish-size.surge.sh/

Screenshots for the change:
s1

### CODE REVIEW

**Comment by Akshat-Jain** [comment]
@PrP-11 There are a lot of places where changes need to be done (mainly CSS issues). For example : 
- Increase the space between the left menu list and the right area. 
- Match the hr lines so that they look exactly like how they do on chat.susi.ai
- Change the positioning of "Save" button in each tab to match it as it is in chat.susi.ai.
- In the individual tabs, make the right area look exactly like in chat.susi.ai. For example, in the Account tab, see the gap between the tab heading (Account Setting) and the topmost subheading (User Name).
- Change "Account Setting" to "Account Settings" in the Account tab
- Change "Save" to "Save Changes" in each tab to match it with chat.susi.ai.
- Currently, all the "Save" buttons are enabled by default, even if there is no change to save. Please take care of it and implement the functionalities for all the tabs (Might be done in another PR).
- Please look at other minor CSS details carefully and match them with chat.susi.ai.

@anshumanv @akshatnitd @hkedia321 @DNS-404 Please review. Thanks :-)

**Comment by PrP-11** [comment]
@mariobehling I have updated it. Please check again. Thanks.

**Comment by DNS-404** [comment]
Agreed with @Akshat-Jain for disabling `Save` buttons by default.

**Comment by DNS-404** [comment]
Apparently the darker background is due to a bug. Checkout issue https://github.com/fossasia/chat.susi.ai/issues/1363.

**Comment by mariobehling** [comment]
> @Akshat-Jain @DNS-404 this PR focuses on displaying settings and improving CSS, the enabling and disabling of save button will be functional when save changes feature will be implemented after this PR gets implemented. Thanks.

I don't understand why all this takes such a long time, if we just want the same thing that we already have in another repo. Things should just work.

> Apparently the darker background is due to a bug. Checkout issue https://github.com/fossasia/chat.susi.ai/issues/1363.

Gray background is the default one.

**Comment by PrP-11** [comment]
@mariobehling I have changed the background to grey. 
I thought first we should be able to display all settings correctly with same CSS as on chat.susi. I am working on saving settings and implement it as well. Thanks.

**Comment by mariobehling** [comment]
> I thought first we should be able to display all settings correctly with same CSS as on chat.susi. 

Yes, it is a bug recently introduced in the chat. Please ensure the CSS stay aligned.

@DNS-404 Please help as well.

**Comment by PrP-11** [comment]
@mariobehling Since the CSS now aligns with chat.susi and background is changed to grey, this can be merged now. Thanks.

**Pull request merged**
