### PR TITLE
Fixed Responsive Design of Login Page

### LINKED ISSUE #497: Login Page responsive design fix
**Actual Behaviour**

When screen size is decreased, responsive design problems occur. 

**Expected Behaviour**

Responsive design should be able to handle the screen size change.

**Steps to reproduce it**

Decrease the screen size.

**Screenshots of the issue**

screenshot from 2018-09-10 18-58-33

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by rossoskull**
Fixes #497 
Changes: When login page width is decreased, the responsive design works fine now.
- Added a media query to handle the squeeze.

Surge Deployment Link: https://pr-498-fossasia-susi-accounts.surge.sh

Screenshots for the change:

screenshot from 2018-09-10 21-16-13

@anshumanv @akshatnitd @Akshat-Jain @DNS-404  please review.
Thanks!

### CODE REVIEW

**Comment by rossoskull** [comment]
On the signup page, the text comes up at the top, so I thought this would make the design consistent.

**Comment by rossoskull** [comment]
@akshatnitd I've done the changes and also squashed the commits, please take a look at them - https://pr-498-fossasia-susi-accounts.surge.sh/

Codacy is failing because of the use of !important. I tried to do it without !important, but the style isn't reflected. Any suggestions?
Thanks! :)

**Comment by akshatnitd** [comment]
@rossoskull Instead of using important with width property, try adding a margin that is needed at the smallest screen size and it should work for all the cases.

**Comment by rossoskull** [comment]
@akshatnitd Done, thanks :)

**Comment by rossoskull** [comment]
Done :+1:

**Pull request merged**
