### PR TITLE
settings: make menu and description heights consistent

### LINKED ISSUE #718: heights of menu and account description are uneven
**Actual Behaviour**

heights of menu and account description are uneven

**Expected Behaviour**

It should be even

**Screenshots of the issue**

image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AdityaSrivast**
Fixes #718 
Changes: Currently the heights of menu and account description on settings page are uneven. It should be even.

Surge Deployment Link: https://pr-719-fossasia-susi-accounts.surge.sh

Screenshots for the change: [Add here screenshots depicting the change.]

image

### CODE REVIEW

**Comment by AdityaSrivast** [comment]
@plxity Which browser are you using?

**Comment by plxity** [comment]
@AdityaSrivast Chrome.

**Comment by AdityaSrivast** [comment]
@plxity Its working fine for me in chrome. 
@AakashMallik how about you?

**Comment by AdityaSrivast** [comment]
@akshatnitd made the changes

**Comment by AdityaSrivast** [comment]
@samagragupta @plxity @AakashMallik  Can you please review?

**Pull request merged**
