### PR TITLE
account verification link

### LINKED ISSUE #136: A route for the e-mail verification link
**Actual Behaviour**

Clicking the e-mail verification link redirects to a link which has the JSON data

**Expected Behaviour**

A route is to be generated for the account verification link which redirects to the accounts.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by DravitLochan**
fixes #136

### CODE REVIEW

**Comment by DravitLochan** [comment]
success

**Comment by DravitLochan** [comment]
success
error

**Comment by mariobehling** [comment]
* Please write sentences in standard English without capitals where they are not needed. 
* Also avoid lots of exclamation marks.
* Instead of adding "Maybe .. is the error", add the error message below.

**Comment by mariobehling** [comment]
Use: 
1. Thank you, your account is now verified. Please login to continue.
2. An error occurred. The error message is `[add system error message here]`.

**Comment by DravitLochan** [comment]
@mariobehling I've updated the success message but I since data is in jsonp format, it is not possible to catch the error message. So I have put 'An error occurred. Please try again' as error message.

**Comment by mariobehling** [comment]
Ok, so why is there no full stop at the end of a sentence?

> An error occurred. Please try again

Please resolve conflicts.

**Pull request merged**
