### PR TITLE
Added Email Id in the Logged in window and fixed multiple small issues

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes issue #145 
Fixes issue #180 
Fixes issue #177 
Fixes issue #174 
Fixes issue #173 
Fixes issue #171 

Changes: Displays email Id when logged in.
                 And fixed multiple small issues.

Surge Deployment Link: http://fixes.surge.sh/

Screenshots for the change:
screen shot 2018-03-02 at 1 41 58 am

screen shot 2018-02-16 at 2 38 06 am

screen shot 2018-03-02 at 6 42 33 pm

### CODE REVIEW

**Comment by DravitLochan** [comment]
@harsh-jindal Looks good! Merge all the changes in this one and close other PRs.

**Comment by harsh-jindal** [comment]
@DravitLochan Okay.

**Comment by harsh-jindal** [comment]
@DravitLochan Merged all the small issue PR's .

**Comment by DravitLochan** [comment]
@harsh-jindal Codacy test is failing. Please Check that.

**Comment by harsh-jindal** [comment]
@DravitLochan I checked it. It shows 1 warning but when I try to see the logs they don't load.
screen shot 2018-03-03 at 10 47 48 pm

**Comment by harsh-jindal** [comment]
@DravitLochan 
screen shot 2018-03-11 at 4 05 29 am
This is why codacy test is failing.

**Comment by harsh-jindal** [comment]
@DravitLochan Please Review

**Comment by DravitLochan** [comment]
@harsh-jindal conflicts!

**Comment by harsh-jindal** [comment]
@DravitLochan resolved conflicts

**Pull request merged**
