### PR TITLE
UI Tweaks For Sign Up Page#482

### LINKED ISSUE #482: UI Fixes for Sign Up Page
**Actual Behaviour**

Change sign up UI

**Expected Behaviour**

Some tweaks in sign up page

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #482 
Changes: 

Some UI Tweaks for sign up page

- Fixed font-size
- Spacing of text
- Minor details can be seen in screenshot

Surge Deployment Link: https://pr-482-fossasia-susi-accounts.surge.sh

Screenshots for the change:
screen shot 2018-09-04 at 2 23 09 am

### CODE REVIEW

**Comment by rossoskull** [comment]
Hey @fragm3 ! For widescreens, it looks great, but when the screen size is decreased, there are some problems with responsiveness. Please look into it.

screenshot from 2018-09-04 22-57-05screenshot from 2018-09-04 22-57-22

**Comment by fragm3** [comment]
@akshatnitd I have updated the PR, have a look.

**Comment by fragm3** [comment]
@rishiraj824 Updated link: https://pr-482-1-fossasia-susi-accounts.surge.sh

**Comment by fragm3** [comment]
@akshatnitd done

**Comment by fragm3** [comment]
@Akshat-Jain the merge commit does not come while squashing. Its fine this way?

**Comment by tabesin** [comment]
Please open a new ticket for the responsiveness challenges.

**Pull request merged**
