### PR TITLE
Password doesn't accept space

### LINKED ISSUE #642: Accepts whitespace in password
**Actual Behaviour**
While signing up, if you put several whitespace in password, it still shows a message showing successful signup.

**Expected Behaviour**
Space should not be allowed in a password. 

**Steps to reproduce it**
Simply try to sign up with 6 or more blank space.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by AvaniVerma**
Fixes #642 

Changes: 
Now the user cannot bypass security checks by entering whitespace to increase character count.

Surge deployment link : https://pr-661-fossasia-susi-accounts.surge.sh/

### CODE REVIEW

**Comment by AvaniVerma** [comment]
@fragm3  Here : https://pr-661-fossasia-susi-accounts.surge.sh/

**Comment by AvaniVerma** [comment]
@anshumanv I think, mid spaces must be removed.  Not doing so would be a security loophole. Allowing mid spaces would allow   _"a                           b"_   as a valid password.

**Comment by anshumanv** [comment]
Refer - https://stackoverflow.com/questions/632167/should-users-be-allowed-to-entered-a-password-with-a-space-at-the-beginning-or-e

I think it's better to leave the password untouched. 😅

**Comment by AvaniVerma** [comment]
I read the document. Thanks for the link.
Well whitespace in password can be confusing in some situations. For one, you can't copy paste it because you won't know whether it has a leading space or not. Users will have to remember whether it's a space or a tab. Also, how many characters are occupied by whitespace continuously. 
However, it's only a suggestion. Final decision about merging this PR or not depends on the team.

**Comment by Orbiter** [comment]
please resolve conflicts

**Comment by Orbiter** [comment]
My thoughts about whitespaces:
- they should be either not allowed
- or they should be untouched.
Special case are spaces at beginning or end of the phrase, which should be trimmed.
That means passwords cannot consist only of spaces.

**Comment by AvaniVerma** [comment]
Added a new PR that trims the password from ends.

**Pull request closed without merging**
