### PR TITLE
Fix issues with responsiveness of start page

### LINKED ISSUE #244: Implement new account start page
Here is a design idea for the new account start page inspired by Twitter and Google Assistant. Please implement it.

Ensure the bottom bar is the same as on https://chat.susi.ai/overview and the top bar the same as on https://skills.susi.ai

screenshot from 2018-05-25 23-13-05

### PR DESCRIPTION
**Pull request by PrP-11**
Fixes #244 
Changes: 
- Fix responsiveness issues of login page
- Remove indents from input fields

Surge Deployment Link: https://pr-289-fossasia-susi-accounts.surge.sh

Screenshots for the change:
l1

### CODE REVIEW

**Comment by AnupKumarPanwar** [comment]
image

1. The anchor tag for forget password is extending beyond the text. Hover the cursor below email input box, the pointer type cursor will appear.
2. The whole input fields are not clickable in the desktop view. For example try the focus on the input box by clicking on its upper part.

**Comment by PrP-11** [comment]
@AnupKumarPanwar Fixed the problem. Please review.

**Comment by akshatnitd** [comment]
This is how the page looks on mobile view. Please add some padding at the top of input field.

screenshot from 2018-06-26 18-02-05

**Comment by PrP-11** [comment]
@akshatnitd Made the changes. Please check again. Thanks
s1

**Pull request merged**
