### PR TITLE
First step in migrating towards react, installed all the dependencies & travis Cli is setup.

### PR DESCRIPTION
**Pull request by jyoth1raditya**
Makes a simple react app with all dependencies and file.
This PR is first step in Issue #42, towards migration to react.
This PR also fixes Issue #47,  steting up travis cli to React app accounts.susi.ai.

### CODE REVIEW

**Comment by jyoth1raditya** [comment]
@DravitLochan Please review and suggest changes

**Comment by jyoth1raditya** [comment]
@DravitLochan You can check the code here : https://github.com/jyoth1raditya/accounts.susi.ai/tree/d

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by rishiraj824** [comment]
@jyoth1raditya Can you use `surge` to deploy your build folder
You can follow the tutorial here. 
https://medium.freecodecamp.com/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089

**Pull request closed without merging**
