### PR TITLE
Fixes #249 Implement new UI for sign up page

### LINKED ISSUE #249: Implement new sign up page
**Actual Behaviour**
Currently its UI is old. 

**Expected Behaviour**
It should be in sync with new UI of the Login page.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by PrP-11**
Fixes #249 

Changes: Implemented new UI for Sign Up page

Surge Deployment Link: http://erratic-picture.surge.sh/

Screenshots for the change:
signup page

### CODE REVIEW

**Comment by mariobehling** [comment]
* Logo size and height of top bar not matching height of chat.susi.ai
* Don't include "settings" in drop-down burger menu if not logged in
* Bottom bar height and alignment not matching https://chat.susi.ai/overview

**Comment by PrP-11** [comment]
@akshatnitd Please click on Signup button to view changes for Sign Up page. Thanks.

**Comment by PrP-11** [comment]
@mariobehling Logo size and height of SUSI on top and bottom bar are corrected. Issue related to settings is created here #253 .

**Comment by PrP-11** [comment]
@mariobehling I am working on it. Can this be merged as work in progress and will create a PR as the css is improved. Thanks.

**Comment by mariobehling** [comment]
Merging as WIP. Thanks.

**Comment by PrP-11** [comment]
@mariobehling Thanks. It's of great help for me.

**Pull request merged**
