### PR TITLE
Broken Navigation bar fixed

### PR DESCRIPTION
**Pull request by DravitLochan**
Fixes issue #12, #7  

Changes: removed http.getJSON call and added AJAX jsonp call to populate navigation bar.

### CODE REVIEW

**Comment by DravitLochan** [comment]
@jyoth1raditya @dynamitechetan @saurabhjn76 @chashmeetsingh Please review!

**Comment by chashmeetsingh** [comment]
@DravitLochan is it deployed somewhere with the fix? Please add a link?

**Comment by DravitLochan** [comment]
@chashmeetsingh Will deploy it and add a link.

**Comment by mariobehling** [comment]
@DravitLochan Please also ping others to get reviews. We need to engage the team in this project as well.

**Comment by DravitLochan** [comment]
@Manveer695 @isuruAb @betterclever @rishiraj824 @uday96  Please review!

**Comment by DravitLochan** [comment]
@chashmeetsingh @betterclever [this](http://erratic-amusement.surge.sh/) is the link to sample deployment.

**Pull request merged**
