### PR TITLE
First step in migrating towards react, installed all the dependencies & travis Cli is setup.

### PR DESCRIPTION
**Pull request by jyoth1raditya**
Makes a simple react app with all dependencies and file.
This PR is first step in Issue #42, towards migration to react.
This PR also fixes Issue #47, setting up travis cli to React app accounts.susi.ai.

Last PR was closed, due to merge conflicts. This PR has no conflicts.

### CODE REVIEW

**Comment by jyoth1raditya** [comment]
@rishiraj824 @uday96 @isuruAb . Deploying this app on surge platform will be done in future changes.
Please review as this PR is base for the app.

**Comment by jyoth1raditya** [comment]
@mariobehling, To go ahead we need this base app. Please merge this.
As you can see in last [PR](https://github.com/fossasia/accounts.susi.ai/pull/48) with same content. No one raised any issues.

**Comment by jyoth1raditya** [comment]
@uday96 @rishiraj824 Here is surge link : http://susi-start.surge.sh/

**Comment by uday96** [comment]
@jyoth1raditya cool :+1:

**Pull request merged**
