### PR TITLE
No icon for email and password text fields #226

### PR DESCRIPTION
**Pull request by SudhanvaMG**
Surge Deployment Link: http://icon-login.surge.sh/
screenshot from 2018-03-24 14-09-34

### CODE REVIEW

**Comment by SudhanvaMG** [comment]
@DravitLochan Created icons for sign up page here . So i will be closing the other PR #235 .

**Comment by SudhanvaMG** [comment]
@harsh-jindal  hey in the main repo of susi chat we have used the same format of the UI , which has been merged . So your suggestion of placing the icon inside a text box with the bored can be taken as a seperate issue as UI improvement for login and signup and can be done there . 
Thank you

**Comment by harsh-jindal** [comment]
@SudhanvaMG Yes, let be a different issue. The icons are not responsiveness. Please check into it. Otherwise it looks good.

**Comment by SudhanvaMG** [comment]
@harsh-jindal  hey the icons are not responsive because the styles of login and sign up are not uniform . I cant change the styles of login from in this issue . Will create a separate issue and edit it there .
I will attach the screenshots of signup page , which is responsive . 

responsive_signup

**Comment by harsh-jindal** [comment]
@SudhanvaMG Please give a test link for responsive signup page.

**Comment by SudhanvaMG** [comment]
@harsh-jindal  please follow this link : http://signup-responsive.surge.sh/signup

The login in page icons is not responsive , which is solved in the PR #238 .

**Comment by harsh-jindal** [comment]
@SudhanvaMG Great work 👍

**Pull request merged**
