### PR TITLE
Added test for Protected Route

### LINKED ISSUE #701: Add test for Protected Route.
**Actual Behaviour**
No test is present for Protected Route.

**Expected Behaviour**

A test should be present for Protected Route.

**Would you like to work on the issue?**

Yes, I would like to work on this.

### PR DESCRIPTION
**Pull request by plxity**
Fixes #701 
Changes: Added Test for Protected Route

Surge Deployment Link: https://pr-702-fossasia-susi-accounts.surge.sh

### CODE REVIEW

**Comment by plxity** [comment]
I think that's a great idea. I'll work on that.

**Comment by AakashMallik** [comment]
@plxity hey bro, check this out https://stackoverflow.com/questions/41531465/how-to-test-react-router-with-enzyme

**Comment by plxity** [comment]
@AakashMallik Even I searched the same thing yesterday. :confused:

**Comment by plxity** [comment]
@AakashMallik  Even I searched the same thing yesterday. :sweat_smile:

**Pull request merged**
